import { createClient } from "@supabase/supabase-js";
import { notFound } from "next/navigation";
import type { Metadata } from "next";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);

const POLICY_TYPE_LABELS: Record<string, string> = {
  privacy: "Privacy Policy",
  terms: "Terms of Service",
  cookies: "Cookie Policy",
  refund: "Refund Policy",
  dmca: "DMCA Policy",
};

interface PageProps {
  params: { code: string };
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { data } = await supabase
    .from("policies")
    .select("app_name, policy_type")
    .eq("short_code", params.code)
    .eq("is_published", true)
    .single();

  if (!data) return { title: "Policy Not Found" };

  return {
    title: `${POLICY_TYPE_LABELS[data.policy_type] || "Policy"} — ${data.app_name}`,
    description: `${POLICY_TYPE_LABELS[data.policy_type]} for ${data.app_name}. Generated by PolicyWiz.`,
  };
}

function renderMarkdown(md: string): string {
  const lines = md.split("\n");
  return lines
    .map((line) => {
      if (line.startsWith("### "))
        return `<h3 class="text-lg font-semibold text-white mt-6 mb-2">${line.slice(4)}</h3>`;
      if (line.startsWith("## "))
        return `<h2 class="text-xl font-bold text-white mt-8 mb-3">${line.slice(3)}</h2>`;
      if (line.startsWith("# "))
        return `<h1 class="text-2xl font-bold text-white mt-4 mb-4">${line.slice(2)}</h1>`;
      if (line.startsWith("- "))
        return `<li class="text-gray-300 ml-4">${line.slice(2)}</li>`;
      if (line.trim() === "") return "<br/>";
      const processed = line
        .replace(/\*\*(.+?)\*\*/g, '<strong class="text-white">$1</strong>')
        .replace(/\*(.+?)\*/g, "<em>$1</em>");
      return `<p class="text-gray-300 leading-relaxed">${processed}</p>`;
    })
    .join("");
}

export default async function PublicPolicyPage({ params }: PageProps) {
  const { data: policy, error } = await supabase
    .from("policies")
    .select("*")
    .eq("short_code", params.code)
    .eq("is_published", true)
    .single();

  if (error || !policy) {
    notFound();
  }

  return (
    <div className="py-10 px-4">
      <div className="max-w-3xl mx-auto">
        <div className="bg-yellow-500/10 border border-yellow-500/30 rounded-lg p-3 mb-6">
          <p className="text-yellow-200 text-sm text-center">
            ⚠️ This policy was generated by PolicyWiz and is a template — not
            legal advice. Consult a qualified attorney for compliance.
          </p>
        </div>

        <article
          className="bg-gray-900 border border-gray-800 rounded-xl p-8 sm:p-12"
          dangerouslySetInnerHTML={{ __html: renderMarkdown(policy.content) }}
        />

        <div className="text-center mt-8">
          <p className="text-sm text-gray-600">
            Generated by{" "}
            <a href="/" className="text-brand-400 hover:underline">
              PolicyWiz
            </a>{" "}
            — Legal policy generator for indie hackers
          </p>
        </div>
      </div>
    </div>
  );
}
